# Model parameters
arch: resnet18
# Datamodule parameter
dataset_name: imagenette160 #
dataset_path: #if None, default dataset path is ~/datasets/[datamodule.dataset_name]
num_classes: 10

# Optim parameters
epochs: 2
batch_size: 32
lr: 0.1
precision: 32 #16 or "bf16"
# Logging parameters
wandb:
  project: pytorch-template
  name: run1 # use for W&B run name and for the checkpoint name

gpu:
  nb_gpus: 1
  strategy:  #  nothing for single gpu training, "ddp" for DistributedDataParallel
# Other parameters
seed: 42
nb_workers: 8
resume: False
